#!/bin/bash

set -e

export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export PYTHONPATH=$SNAP/lib/python3.5/site-packages/

exec "$SNAP/bin/gunicorn" --chdir "$SNAP/myproj" --bind unix:/tmp/django-gunicorn.sock wsgi:app --error-logfile /var/snap/django-gubicorn/common/log/gunicorn-error.log --access-logfile /var/snap/django-gunicorn/common/log/gunicorn-access.log "$@"
