name: django-gunicorn
version: '0.1' 
summary: django-gunicorn
description: |
  Django Example

grade: stable
confinement: classic

apps:
  django-gunicorn:
    environment:
      DJANGO_SECRETS_DIR: $SNAP_COMMON/django_secrets
    command: wrappers/django-gunicorn
    daemon: simple
  nginx:
    daemon: simple
    command: wrappers/nginx-run
    reload-command: wrappers/nginx-reload
parts:
  django-gunicorn:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [libpq-dev,libssl-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/django-gunicorn
      python3 ./manage.py collectstatic --no-input
      cp -r ./* $SNAPCRAFT_PART_INSTALL/django-gunicorn/
  wrappers:
    # Build after django-gunicorn for debugging purposes.
    # We want django-gunicorn to fail first in dev so we don't have
    # to wait on these parts to complete before we know what has gone wrong.
    # the after clause/stanza below can be remove in prod and/or once the nginx
    # snap is decoupled from this one
    after: [django-gunicorn]
    plugin: dump
    source: snap/wrap/
  nginx-wrap:
    # Build after django-gunicorn for debugging purposes.
    # We want django-gunicorn to fail first in dev so we don't have
    # to wait on these parts to complete before we know what has gone wrong.
    # the after clause/stanza below can be remove in prod and/or once the nginx
    # snap is decoupled from this one
    after: [django-gunicorn]
    plugin: nginx
    source: snap/templates/
    install: |
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      mv ./nginx.conf.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
