name: django-gunicorn
version: '0.1' 
summary: django-gunicorn
description: |
  Django Example

grade: stable
confinement: classic

apps:
  django-gunicorn:
    environment:
      DJANGO_SECRETS_DIR: $SNAP_COMMON/django_secrets
    command: wrappers/django-gunicorn
    daemon: simple
  nginx:
    daemon: simple
    command: wrappers/nginx-run
    reload-command: wrappers/nginx-reload
parts:
  django-gunicorn:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [libpq-dev,libssl-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/django-gunicorn
      python3 ./manage.py collectstatic --no-input
      cp -r ./* $SNAPCRAFT_PART_INSTALL/django-gunicorn/
  wrappers:
    after: [django-gunicorn]
    plugin: dump
    source: snap/wrap/
  nginx-wrap:
    after: [django-gunicorn]
    plugin: nginx
    source: snap/templates/
    install: |
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      mv ./nginx.conf.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
